IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'CLIENTES') AND NAME = 'CPF')
	BEGIN
		ALTER TABLE CLIENTES ADD CPF VARCHAR(11)
		PRINT('Coluna "CPF" foi adicionada a tabela CLIENTES')
	END
ELSE
	PRINT('Coluna "CPF" JÁ EXISTE na tabela CLIENTES')
GO